### ISSUE TITLE
Using EF Toolkit with Asp.net Identity?

### ISSUE THREAD

**Issue by zahik** [thomasgalliker/EntityFramework.Toolkit#1]
Hi Thomas.
Thank you for your Great work!

I want to use EF Toolkit with asp.net Identity - i.e. i want to inherit
my dbcontext (for example ShopContext ) from IdentityDbContext<ApplicationUser>.
How can i do it with your tool?
(I tried ShopContext: DbcontextBase<IdentityDBContext<user>>, IShopcontext )
but no avail.

Can you help? (for the general if i want to inherit my DB from another DB and use your DBContextBase<>?

Regards.
Zahi.

**Comment by zahik** [comment]
Anyone?

**Comment by thomasgalliker** [comment]
Thank you for your question. Obviously, I did not get a notification, so, sorry for not responding.

DbContextBase<T> does already derive from DbContext<T> so I dont think you can wrap DbContexts as you proposed. Do you have sample code so I can try by myself?

**Comment by zahik** [comment]
Thanks Thomas, It's better late then nothing :)
(I just got now email ...)
I don't have specific code to give you,
but as a REAL world app, you should use Identity DB for logins.
How you intend to implement that?
(on normal use of EF i inherited from IdentityDBContext<ApplicationUser>)
Regards.
Zahi

**Comment by thomasgalliker** [comment]
Hi Zahik. I tried it now, finally. You can implement a custom UserStore, which is accessing any datacontext - not even necessarily an EF context to read/write identity information. I'm using this approach in this sample repository: https://github.com/thomasgalliker/spa-webapi-angularjs

Do you think this helps you? May be too late now...
