### ISSUE TITLE
Testing with in-memory providers in Entity Framework

### ISSUE THREAD

**Issue by superdeaf** [thomasgalliker/EntityFramework.Toolkit#10]
Your framework does not seem to support any in-memory capabilities.
Such as Microsoft.EntityFrameworkCore.InMemory for its EF-Core counterpart.
Are there any plans to integrate support for any in-memory providers?

I think the possible performance gains, especially regarding repetitive activities like automated testing, would greatly benefit productivity.
If you need any further information on this topic, I would like to recommend the following reads:

- https://www.stevefenton.co.uk/2015/11/using-an-in-memory-database-as-a-test-double-with-entity-framework/
- https://entityframework-classic.net/provider-effort-inmemory
- https://github.com/zzzprojects/EntityFramework-Effort

**Comment by thomasgalliker** [comment]
That‘s true. I‘m not a big fan of in-memory providers for testing since they don‘t reflect the truth the same way as a real database does. IQueryable Get() works differently on an in-memory provider compared to a real SQL database.
Now, to gain speed in integration tests I recommend to share a comman DbContext across multiple test cases.
For isolated unit tests I mostly use Moq to mock the I*Repository interfaces with synthetic test data.

**Comment by sherrif10** [comment]
@thomasgalliker its as if you are trying to mean i run a way from testing my class because am a bit scally

**Comment by thomasgalliker** [comment]
@superdeaf I'm using this EFCore.Toolkit with AspNetCore and I was giving Microsoft.EntityFrameworkCore.InMemory a chance - but again I found a better solution. Read this blog page, especially his third approach "EF Sqlite provider with database file". I essentially replace the MS SQL provider with an SQLite provider (not the in-memory sqlite provider but a real, file-based sqlite provider) when the web backend is started for integration testing.

https://raaaimund.github.io/tech/2019/05/08/aspnet-core-integration-testing/

@sherrif10 not sure what you mean :) pretty sure you're testing it 💯 👍

**Comment by sherrif10** [comment]
Thanks am also trying to get acquited to testing classes that dependant
with in memory database like forexample testing  service classes like
personServiceImplTest which embedds in memory database
